[[commit_types]]
name = "feat"
description = "A new feature"

[[commit_types]]
name = "fix"
description = "A bug fix"

[[commit_types]]
name = "docs"
description = "Documentation only changes"

[[commit_types]]
name = "style"
description = "Changes that do not affect the meaning of the code"

[[commit_types]]
name = "refactor"
description = "A code change that neither fixes a bug nor adds a feature"

[[commit_types]]
name = "perf"
description = "A code change that improves performance"

[[commit_types]]
name = "test"
description = "Adding missing tests or correcting existing tests"

[[commit_types]]
name = "build"
description = "Changes that affect the build system or external dependencies"

[[commit_types]]
name = "ci"
description = "Changes to our CI configuration files and scripts"

[[commit_types]]
name = "chore"
description = "Other changes that don't modify src or test files"

[[commit_types]]
name = "revert"
description = "Reverts a previous commit"
