[hooks]
pre-commit = "cargo test --locked"
pre-push = "cargo check --locked && cargo clippy --locked -- -D warnings && cargo fmt --all -- --check"
prepare-commit-msg = "exec < /dev/tty && cargo run -- --hook || true"

[logging]
verbose = true
