name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release binary for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [x86_64-osx, x86_64-unknown-linux-musl, x86_64-pc-windows-gnu]
        include:
          - os: macos-latest
            target: x86_64-osx
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
      - name: Install libssl-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install libssl-dev

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.60.0

      - uses: actions/checkout@v1
      - name: Build
        run: ci/build.sh release ${{ matrix.target }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/tar/koji.tar.gz
          tag: ${{ github.ref }}
          asset_name: koji-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz
