name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-to-github:
    name: Release to GitHub for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - {
              os: ubuntu-latest,
              target: x86_64-unknown-linux-gnu,
              use-cross: true,
            }
          - {
              os: ubuntu-latest,
              target: aarch64-unknown-linux-gnu,
              use-cross: true,
            }
          - { os: macos-latest, target: x86_64-apple-darwin, use-cross: false }
          - { os: macos-latest, target: aarch64-apple-darwin, use-cross: false }
          - {
              os: ubuntu-latest,
              target: x86_64-pc-windows-gnu,
              use-cross: true,
            }
          - {
              os: windows-latest,
              target: x86_64-pc-windows-msvc,
              use-cross: false,
            }
          - {
              os: windows-latest,
              target: aarch64-pc-windows-msvc,
              use-cross: false,
            }

    steps:
      - name: Install dependencies
        shell: bash
        run: |
          if [[ ${{ matrix.job.target }} == "aarch64-unknown-linux-gnu" ]]; then
              sudo apt update
              sudo apt install -y binutils-aarch64-linux-gnu
          fi

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.job.use-cross }}
          args: --release --target ${{ matrix.job.target }}

      - name: Package final binary
        shell: bash
        env:
          TARGET: ${{ matrix.job.target }}
          PROJECT_NAME: koji
          OS_NAME: ${{ matrix.job.os }}
        run: ./meta/ci/package.sh

      - name: Release assets
        uses: softprops/action-gh-release@v1
        with:
          files: koji-*-${{ matrix.job.target }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-to-cargo:
    name: Release to Cargo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CARGO_API_KEY }} --allow-dirty
